# Generated by Django 6.0.2 on 2026-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Bootstrap icon class (misali: bi-heart-pulse)', max_length=50),
        ),
    ]
